### ISSUE TITLE
Create About us page for LDL.

### ISSUE THREAD

**Issue by rishhavv** [Repozo/ldl-ngo#3]
you can copy and paste all the info from the [this page](https://www.lightdeliteracy.com/about-us/)

no need to clone, you can get as creative as you want. try experiment and do something new :)

**Comment by rishhavv** [comment]
You can include "about us" page in sidebar

**Comment by CyrusThapa11** [comment]
i can work on this

**Comment by rishhavv** [comment]
@copyNinja1219 go ahead

**Comment by CyrusThapa11** [comment]
Sir I have made the about page copyNinja1219

**Comment by rishhavv** [comment]
issues closed with successful @copyNinja1219 PR
